services:
  noob-fighters-node:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
